### ISSUE TITLE
'start' and 'end' seem to be same hour for tour mode choice estimation data bundle for all records. 

### ISSUE THREAD

**Issue by stefancoe** [psrc/psrc_activitysim#15]
Check the survey conversion?

**Comment by bricegnichols** [comment]
Bug fix, wrong column name in [joint_tour_expr.csv](https://github.com/psrc/psrc_activitysim/commit/acfd32009471100b50a39cfb593fab86c26cb672#diff-74c702f623afefaf30bab96b3ce6d8d9e31cfe36e1157e3c8011c2416f581b50)

Closed by: https://github.com/psrc/psrc_activitysim/commit/acfd32009471100b50a39cfb593fab86c26cb672
