### ISSUE TITLE
Missing HH income in survey

### ISSUE THREAD

**Issue by stefancoe** [psrc/psrc_activitysim#16]
Should we impute?

**Comment by bricegnichols** [comment]
Imputing survey data using K-Nearest Neighbor algorithm: https://github.com/psrc/psrc_activitysim/blob/main/scripts/survey_conversion/activitysim_survey_conversion_multiday.py#L545-L558

**Comment by bricegnichols** [comment]
Closed with https://github.com/psrc/psrc_activitysim/commit/2fb65596ede627f22212bcb140657effeef38a7d
