### ISSUE TITLE
Columns mismatch in tour_mode_choice.csv

### ISSUE THREAD

**Issue by stefancoe** [psrc/psrc_activitysim#18]
@tedlini In the dev_RSG branch, utilities for commuter rail & ferry were listed under the WALK_LR columns.:
https://github.com/psrc/psrc_activitysim/blob/a67df0f34a24ff0d25d5ed81689175570a6030cc/configs_dev/tour_mode_choice.csv

I fixed this with this commit:
https://github.com/psrc/psrc_activitysim/commit/8aab45c16eebac7e26742982e79628e0f0dc3546

But can you review to make sure my changes look good? Thanks!

**Comment by tedlini** [comment]
@stefancoe The fix looks good. I made a similar fix for trip_mode_choice.csv https://github.com/psrc/psrc_activitysim/commit/a7d0f2083deec08142ef102d26a6de3abed773d2

**Comment by stefancoe** [comment]
@tedlini Thanks!
